# Python

#### Немного совсем простых примеров про numpy и pandas:

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a**2

array([ 1,  4,  9, 16])

In [5]:
a*4

array([ 4,  8, 12, 16])

In [6]:
a > 3

array([False, False, False,  True], dtype=bool)

In [7]:
a[a>2]

array([3, 4])

In [10]:
df = pd.DataFrame(data = [[1,2,3],[2,3,2],[5,5,1]], columns = ['a', 'b', 'c'])

In [11]:
df

a  b  c
0  1  2  3
1  2  3  2
2  5  5  1

In [12]:
df.a

0    1
1    2
2    5
Name: a, dtype: int64

In [14]:
df.loc[[0,2], ['a', 'c']]

a  c
0  1  3
2  5  1

In [21]:
df['d'] = [0,0,0]
df

a  b  c  d
0  1  2  3  0
1  2  3  2  0
2  5  5  1  0

### Про классы и методы и вот это всё

In [65]:
class Nums:
    def __init__(self, nums = []):
        self._nums = nums
    def display(self):
        print self._nums
    def sum(self):
        return sum(self._nums)

class MoreNums(Nums):
    def __init__(self, nums = []):
        self._nums = nums
    def product(self):
        res = 1
        for i in self._nums:
            res *= i
        return res

In [27]:
x = Nums

In [28]:
x

<class __main__.Nums at 0x1068b4668>

In [30]:
x = Nums()

In [31]:
x

<__main__.Nums instance at 0x10695eef0>

In [32]:
x.display()

[]


In [33]:
y = Nums([1,2,3])

In [34]:
y.sum()

6

In [35]:
y.display()

[1, 2, 3]


In [66]:
z = MoreNums([1,2,3])

In [67]:
z.display()

[1, 2, 3]


In [68]:
z.sum()

6

In [69]:
z.product()

6

## Немного про лямбды

In [48]:
array = range(50)+range(50)+range(50)+range(50)+range(50)

In [52]:
%timeit a = [i**10 for i in array]

10000 loops, best of 3: 33.6 µs per loop


In [53]:
%%timeit
a = []
for i in array:
    a.append(i**10)

10000 loops, best of 3: 57.6 µs per loop
